export { NameField } from '@core/Components/InputFields/NameField'
export { EmailField } from '@core/Components/InputFields/EmailField'
export { YearField } from '@core/Components/InputFields/YearField'
export { NumberField } from '@core/Components/InputFields/NumberField'
export { PasswordField } from '@core/Components/InputFields/PasswordField'
